### ISSUE TITLE
We should not only bench them on node, but also on real browsers

### ISSUE THREAD

**Issue by CarterLi** [DavidCai1993/ES6-benchmark#8]
As mentioned [before](https://github.com/DavidCai1993/ES6-benchmark/pull/7), they may have different performance.
The best way is using [jsperf](jsperf.com)

Several cases done by me:
1. http://jsperf.com/merging-objects-vs-for-in
2. http://jsperf.com/string-startswith-vs-regexp-test **ES6 wins on FF & Safari**
3. http://jsperf.com/native-promise-vs-bluebird
4. http://jsperf.com/template-string-vs-use-add-v2 **ES6 wins on all 3 browsers**
5. http://jsperf.com/declare-a-class **ES6 wins on FF**
6. http://jsperf.com/spread-operator-vs-apply

**Comment by DavidCai1111** [comment]
For now this project is just focus on the perf of some popular es6 features on node and chakra-node,  just like it's description : "A benchmark for some popular ES6 features in Node.js ( V8 / Chakra ) ."
